glue.c: Remove multiple definitions when using musl
unikraft/lib-libcxx pull request #17
Opened 2022-10-29 10:09 UTC by StefanJum

Musl provides the `catclose`, `catopen` and `catgets` functions, so when building `libcxx` with musl the linking fails.

This commit only defines the needed functions when `LIBMUSL` is not selected.

Closes: #16 

Signed-off-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-11-03 14:00 UTC, mariasfiraiala approved these changes
Thanks @StefanJum .
All good on my part, works as expected when tested with #19.

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2022-11-15 10:41 UTC, razvand requested changes
@StefanJum , please use `Musl` instead of `musl` in the commit message.

2022-11-15 10:47 UTC, StefanJum commented
Done @razvand.

2022-11-15 10:51 UTC, razvand approved these changes
Thanks, @StefanJum 

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2022-11-18 08:25 UTC, closed without merging