include/math.h: Add libcxx math.h header
unikraft/lib-libcxx pull request #22
Opened 2022-11-04 11:07 UTC by StefanJum

When building `libcxx` with musl, some
undefined functions errors appear because
the musl math.h header is used.

`cmath` looks for some funtions defined in
an anonymous namespace, but they are defines
as macros within the `musl` headers.
This leads to errors since the macros can
not match the required functions.

The functions are defined in `libcxx`
headers, but they are not processed since the
`musl` headers are prioritised.
We cannot prioritise the `libcxx` headers since
it leads to a lot of issues similar to this one.

Closes: #15 

Signed-off-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-11-05 19:50 UTC, mariasfiraiala approved these changes
Looks good to me! Tested the changes with `musl` using the `helloworld-cpp` app and it works as expected. 
Thanks a lot @StefanJum .

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2022-11-15 09:49 UTC, razvand requested changes
Hi, @StefanJum , could you please use a saner column length for the commit description? Closer to 72/80 characters wide.

2022-11-15 10:11 UTC, StefanJum commented
Done @razvand

2022-11-18 14:38 UTC, razvand approved these changes
Thanks, @StefanJum 

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2022-11-19 16:29 UTC, closed without merging