patches: Add patch with definition for `vasprintf`
unikraft/lib-libcxx pull request #23
Opened 2022-11-14 10:35 UTC by mariasfiraiala

Compilation step for `__bsd_locale_fallbacks.h` requires having a working definition of `vasprintf`. This symbol is defined in `include/support/ibm/xlocale.h`, however it wouldn't make sense for us to use headers made for `ibm`.

This PR provides a patch that adds the needed function in `include/support/musl`.

Signed-off-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

2022-11-16 11:17 UTC, StefanJum approved these changes
Looks good to me @mariasfiraiala, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-11-19 16:37 UTC, razvand requested changes
@mariasfiraiala , why is this required? `vasprintf` is already defined in `origin/musl-1.1.19/src/stdio/vasprintf.c`:

```
$ grep -rw vasprintf
[...]
./build/libmusl/origin/musl-1.1.19/src/stdio/vasprintf.c:int vasprintf(char **s, const char *fmt, va_list ap)
```

And this causes a conflict. Without your PR everything works OK on my side.

2022-11-19 18:59 UTC, StefanJum requested changes
@mariasfiraiala it seems the `arm` toolchain only complains because the function signature is not found anywhere within `libcxx`. The function is defined in `libmusl.o` in both `x86` and `arm` builds.

I think you can reply the `xlocale.h` patch and just add:
```diff
+int vasprintf(char **strp, const char *fmt, va_list ap);
```

This seemed to work for me for both `x86` and `arm`.

2022-11-19 19:03 UTC, razvand commented
> @mariasfiraiala it seems the `arm` toolchain only complains because the function signature is not found anywhere within `libcxx`. The function is defined in `libmusl.o` in both `x86` and `arm` builds.

@StefanJum , why would it complain? Isn't the same header file with the same function declaration included both on `x86` and on `aarch64`?

2022-11-19 19:08 UTC, StefanJum commented
> @StefanJum , why would it complain? Isn't the same header file with the same function declaration included both on `x86` and on `aarch64`?

@razvand I think `gcc` just gives a warning when not finding the function signature and relies on the linking to solve the actual definition. The same headers are included, when building for `x86` `vasprintf` shows as undefined in `libcxx.o`, but it breaks at compiling for `arm` even if the symbol would be resolved at link time.

```
/media/stefan/projects/unikraft/musl-test/workdir/apps/app-helloworld-cpp/build/libcxx/origin/libcxx-7.0.0.src/include/__bsd_locale_fallbacks.h:123:17: error: 'vasprintf' was not declared in this scope; did you 
mean 'vsprintf'?                                                                                                                                                                                                   
  123 |     int __res = vasprintf(__s, __format, __va);                                                                                                                                                            
      |                 ^~~~~~~~~                                                                                                                                                                                  
      |                 vsprintf                                                                                                                                                                                   
In file included from /media/stefan/projects/unikraft/musl-test/workdir/apps/app-helloworld-cpp/build/libcxx/origin/libcxx-7.0.0.src/include/ostream:140,                                                          
                 from /media/stefan/projects/unikraft/musl-test/workdir/apps/app-helloworld-cpp/build/libcxx/origin/libcxx-7.0.0.src/include/istream:163,                                                          
                 from /media/stefan/projects/unikraft/musl-test/workdir/apps/app-helloworld-cpp/build/libcxx/origin/libcxx-7.0.0.src/include/iostream:40,                                                          
                 from /media/stefan/projects/unikraft/musl-test/workdir/apps/app-helloworld-cpp/helloworld.cpp:1:
```

I'm not sure this is the case, but just providing the function signature in the header solves the error so I'm guessing that could be it.

2022-11-19 20:18 UTC, mariasfiraiala commented
Following @StefanJum 's comment I've changed the patch accordingly. Thanks @razvand for checking the `x86` app too, and apologies for not testing it also.
Please take another look when you find the time.

2022-11-19 21:17 UTC, StefanJum reviewed
Works fine now @mariasfiraiala, thank you.
Please update the commit message since this no longer  provides the function implementation.

2022-11-19 23:05 UTC, mariasfiraiala commented
> Works fine now @mariasfiraiala, thank you. Please update the commit message since this no longer provides the function implementation.

Done. Thanks @StefanJum !

2022-11-20 08:36 UTC, razvand commented
@StefanJum , @mariasfiraiala , I think the issue is an include order issue. The Musl `stdio.h` header contains the declaration of `vasprintf()`:

```
[...]
./build/libmusl/origin/musl-1.1.19/include/stdio.h:int vasprintf(char **, const char *, __isoc_va_list);
```

But somehow it's not included, although it's present in the build, likely it gets passed by the `./build/libcxx/origin/libcxx-7.0.0.src/include/stdio.h` file, that does, however, two `#include_next <stdio.h>`:

```
razvan@yggdrasil:~/.../workdir/apps/app-helloworld-cpp$ grep -r stdio.h | grep next
build/libcxx/origin/libcxx-7.0.0.src/include/stdio.h:#include_next <stdio.h>
build/libcxx/origin/libcxx-7.0.0.src/include/stdio.h:#include_next <stdio.h>
```

```
razvan@yggdrasil:~/.../workdir/apps/app-helloworld-cpp$ find -name stdio.h
./build/include/config/libmusl/stdio.h                         
./build/libcxx/origin/libcxx-7.0.0.src/include/stdio.h     
./build/libmusl/origin/musl-1.1.19/include/stdio.h          
./build/libmusl/include/time/include/stdio.h              
./build/libmusl/include/thread/include/stdio.h              
./build/libmusl/include/stdlib/include/stdio.h                
./build/libmusl/include/stdio/include/stdio.h             
./build/libmusl/include/multibyte/include/stdio.h        
./build/libmusl/include/legacy/include/stdio.h             
./build/libmusl/include/internal/include/stdio.h    
./build/libmusl/include/conf/include/stdio.h              
./build/libmusl/include/crypt/include/stdio.h             
./build/libmusl/include/passwd/include/stdio.h         
./build/libmusl/include/locale/include/stdio.h         
./build/libmusl/include/regex/include/stdio.h          
./build/libmusl/include/misc/include/stdio.h             
./build/libmusl/include/exit/include/stdio.h             
./build/libmusl/include/signal/include/stdio.h          
./build/libmusl/include/unistd/include/stdio.h        
./build/libmusl/include/network/include/stdio.h 
```

So I think some fine tuning of include directives would do the trick. @mariasfiraiala , please spend 1-2 hours on this. If you can't figure it out, let's use the current solution. And please create an issue with what I just showed above, so we can look into that sometime in the future.

2022-11-25 07:52 UTC, StefanJum commented
@mariasfiraiala any updates on this? If not, should we merge it and do a proper fix later on, as @razvand suggested?

2022-11-25 08:31 UTC, razvand commented
@StefanJum , yes, let's do a merge right now and fix it later. @mariasfiraiala , please create an issue to solve the issue later on.

@StefanJum , review it, I'll approve it and that would be it.

2022-11-25 09:01 UTC, StefanJum approved these changes
All good here, thanks @mariasfiraiala.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2022-11-25 09:05 UTC, razvand approved these changes
Thanks, @mariasfiraiala 

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2022-11-25 09:14 UTC, closed without merging